name: Branch Name Validator

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch naming convention
        run: |
          echo "Branch Name: ${{ github.head_ref }}"
          BRANCH_NAME="${{ github.head_ref }}"

          if [[ "$BRANCH_NAME" =~ ^feature-[A-Z]+-[0-9]+-[a-zA-Z0-9-]+$ ]]; then
            echo "Valid branch name."
          else
            echo "Invalid branch name: '$BRANCH_NAME'"
            echo "Required format: feature-<JIRANUM>-<description> (e.g., feature-ABC-123-add-logging)"
            exit 1
          fi

