name: Protect Branches

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Validate branch name
        id: branch_check
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Checking branch name: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^feature-[A-Z]+-[0-9]+-[a-zA-Z0-9-]+$ ]]; then
            echo "Branch name is valid."
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "Branch name is invalid."
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check PR approvals
        id: reviewer_check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          echo "Checking approvals for $PR_URL"

          REVIEW_COUNT=$(gh pr view "$PR_URL" --json reviews -q '.reviews | map(select(.state == "APPROVED")) | length')
          echo "Review count: $REVIEW_COUNT"

          if [[ "$REVIEW_COUNT" -ge 1 ]]; then
            echo "approved=true" >> $GITHUB_OUTPUT
          else
            echo "approved=false" >> $GITHUB_OUTPUT
          fi

      - name: Block merge if policy fails
        if: steps.branch_check.outputs.valid != 'true' || steps.reviewer_check.outputs.approved != 'true'
        run: |
          echo "Blocking PR: Invalid branch name or no approval."
          exit 1

      - name: Allow merge (info only)
        if: steps.branch_check.outputs.valid == 'true' && steps.reviewer_check.outputs.approved == 'true'
        run: |
          echo "PR meets branch naming and approval policy."
