name: Protect PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, review_requested, review_request_removed, assigned]

jobs:
  enforce-pr-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name and reviewer assignment
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const branchName = pr.data.head.ref;
            const isValidBranch = /^feature-[A-Z]+-[0-9]+-[a-z0-9-]+$/.test(branchName);

            if (!isValidBranch) {
              core.setFailed(` Invalid branch name: '${branchName}'. Must follow pattern: feature-ABC-123-desc`);
            }

            const requestedReviewers = pr.data.requested_reviewers;
            const hasReviewer = requestedReviewers.length > 0;

            if (!hasReviewer) {
              core.setFailed(`No reviewer assigned. Please assign at least one reviewer to proceed.`);
            }

            if (isValidBranch && hasReviewer) {
              console.log(" Branch name valid and reviewer is assigned.");
            }
