name: Protect Branches

on:
  push:
    branches: [ main, development, master ]
  workflow_dispatch:

jobs:
  protect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Validate branch name
        id: branch_check
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Checking branch name: $BRANCH_NAME"
          
          if [[ "$BRANCH_NAME" =~ ^(main|master|feature/.*|release/.*)$ ]]; then
            echo "Branch name is valid according to the policy."
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "Branch name does not follow naming policy. Merge is not allowed."
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for reviewers and approvals
        id: reviewer_check
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          PR_URL=$(gh pr list --head "$BRANCH_NAME" --json url -q '.[0].url')
          if [[ -z "$PR_URL" ]]; then
            echo "No pull request found for branch $BRANCH_NAME. Review check cannot proceed."
            echo "approved=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Pull request detected: $PR_URL"
          REVIEW_COUNT=$(gh pr view "$PR_URL" --json reviews -q '.reviews | map(select(.state == "APPROVED")) | length')
          if [[ "$REVIEW_COUNT" -ge 1 ]]; then
            echo "Pull request has received at least one approval."
            echo "approved=true" >> $GITHUB_OUTPUT
          else
            echo "Pull request does not have any approvals yet."
            echo "approved=false" >> $GITHUB_OUTPUT
          fi

      - name: Allow merge if conditions are met
        if: steps.branch_check.outputs.valid == 'true' && steps.reviewer_check.outputs.approved == 'true'
        run: |
          echo "Merge is allowed: valid branch name and approval are both confirmed."

      - name: Block merge due to failing conditions
        if: steps.branch_check.outputs.valid != 'true' || steps.reviewer_check.outputs.approved != 'true'
        run: |
          echo "Merge is blocked due to either an invalid branch name or missing required approval."
          exit 1
