name: Protect PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - review_requested
      - assigned
      - edited

jobs:
  enforce-pr-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR rules
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const branch = pr.data.head.ref;
            const isValidBranch = /^feature-[A-Z]+-[0-9]+-[a-z0-9-]+$/.test(branch);
            const hasReviewers = pr.data.requested_reviewers.length > 0 || pr.data.assignees.length > 0;

            console.log(`Branch: ${branch}`);
            console.log(`Reviewers: ${pr.data.requested_reviewers.length}, Assignees: ${pr.data.assignees.length}`);

            if (!isValidBranch) {
              core.setFailed(`❌ Branch name '${branch}' is invalid. It must match: feature-ABC-123-description`);
            }

            if (!hasReviewers) {
              core.setFailed(`❌ Reviewer is not assigned.`);
            }

            if (isValidBranch && hasReviewers) {
              console.log("✅ All PR rules passed.");
            }
