name: Protect Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name format
        id: branch_check
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^feature-[A-Z]+-[0-9]+-[a-zA-Z0-9-]+$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if reviewer is assigned
        id: reviewer_check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          echo "Checking reviewers for PR #$PR_NUMBER in $REPO"

          REVIEWER_COUNT=$(gh api repos/$REPO/pulls/$PR_NUMBER/requested_reviewers --jq '.users | length')

          if [[ "$REVIEWER_COUNT" -ge 1 ]]; then
            echo "reviewer_assigned=true" >> $GITHUB_OUTPUT
          else
            echo "reviewer_assigned=false" >> $GITHUB_OUTPUT
          fi

      - name: Final gate — block if any condition fails
        if: steps.branch_check.outputs.valid != 'true' || steps.reviewer_check.outputs.reviewer_assigned != 'true'
        run: |
          echo "❌ Merge is blocked: Invalid branch name or no reviewer assigned."
          exit 1
